services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: b1tsized/gcp-dynamic-dns
    network_mode: host
    environment:
      MODE: service
      DNS_NAMES: example.com. www.example.com.
      GOOGLE_PROJECT: your-project-123456
      GOOGLE_APPLICATION_CREDENTIALS: /var/secrets/gcp-keys.json
    volumes:
      - ./gcp-dns-admin-keys.json:/var/secrets/gcp-keys.json:ro
